version: '3'

services:
  feedme:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env:ro
      - feedme-data:/app/public/data
    container_name: feedme
    restart: unless-stopped

volumes:
  feedme-data:
